### ISSUE TITLE
Is it possible to compile cljs files with calvin?

### ISSUE THREAD

**Issue by viebel** [eginez/calvin#6]

**Comment by eginez** [comment]
short answer is yes, technically compilation works, but there are other taks the java cljs compiler performs, those I am still researching. You can take a peek at the cljs-build branch to look at what I am trying to do

**Comment by eginez** [comment]
we can now!

**Comment by eginez** [comment]
calvin now supports the lumo build api that can be used to compile to cljs, please notice there are limitations with the above api
